# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kli < Formula
  desc "A CLI to access, query and manage KAI servers."
  homepage "https://github.com/konstellation-io/kai-kli"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/konstellation-io/kai-kli/releases/download/v0.6.2/kai-kli_0.6.2_darwin-arm64.tar.gz"
      sha256 "f3cce8bd47a76fbe0d2775bf64e53c53315c176d80a07af898890ffbe86d1d6e"

      def install
        bin.install "bin/kli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/konstellation-io/kai-kli/releases/download/v0.6.2/kai-kli_0.6.2_darwin-amd64.tar.gz"
      sha256 "a2d8d690f58631794c3ebc4cb1790054e9f6d30fa5dbf344cd16c5704924bb4d"

      def install
        bin.install "bin/kli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/konstellation-io/kai-kli/releases/download/v0.6.2/kai-kli_0.6.2_linux-arm64.tar.gz"
      sha256 "82fdb756cb685bf92e668a6dacdabcfc7a15451eed4924864210cb4bec0c59d2"

      def install
        bin.install "bin/kli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/konstellation-io/kai-kli/releases/download/v0.6.2/kai-kli_0.6.2_linux-amd64.tar.gz"
      sha256 "047e7fc90184806c2e31467ba871ca6a8f5892357d3ffa6e78264323aa51c36b"

      def install
        bin.install "bin/kli"
      end
    end
  end
end
